server:
  port: 8083

spring:
  application:
    name: settlement-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fx_treasury?currentSchema=fx_object
    username: postgres
    password: postgrespassword
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: fx_object

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true